---
- name: Join various OS systems to domain 4s-technologies.com
  hosts: all
  become: yes
  vars:
    domain_name: "4s-technologies.com"
    domain_user: "administrator@4s-technologies.com"
    domain_password: "SuperSecretPassword!"   # Use Ansible Vault in production
    pc_name: "{{ inventory_hostname }}"

  tasks:

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ pc_name }}"
      when: ansible_os_family != "Windows"

    - name: Join RHEL/Ubuntu/Kali to domain
      block:
        - name: Install required packages for domain join (RHEL/Ubuntu)
          package:
            name:
              - realmd
              - sssd
              - oddjob
              - oddjob-mkhomedir
              - adcli
              - samba-common
              - samba-common-tools
              - krb5-workstation
              - policycoreutils-python-utils
            state: present
          when: ansible_os_family in ['RedHat', 'Debian']

        - name: Discover the domain
          command: realm discover "{{ domain_name }}"
          register: realm_discovery
          changed_when: false

        - name: Join the domain
          command: >
            realm join --user={{ domain_user }} {{ domain_name }}
          args:
            stdin: "{{ domain_password }}"
          when: "'configured' not in realm_discovery.stdout"

      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Set Windows hostname
      win_hostname:
        name: "{{ pc_name }}"
      when: ansible_os_family == "Windows"

    - name: Join Windows host to domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_user }}"
        domain_admin_password: "{{ domain_password }}"
        hostname: "{{ pc_name }}"
        state: domain
      when: ansible_os_family == "Windows"
      register: domain_join

    - name: Reboot Windows after domain join
      win_reboot:
      when: domain_join.changed
